/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SRC1;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shubh
 */
public class EscalationMatrix extends javax.swing.JFrame {
    Connection conn=null;
ResultSet rs = null;
PreparedStatement pst=null;



    /**
     * Creates new form EscalationMatrix
     */
    public EscalationMatrix() {
        initComponents();
        UpdateJTable();
        UpdateJTable2();
       
    }
    
    
    private void UpdateJTable(){
        
        
        //jTable1_pumpdata.setBackground((Color.GREEN));
         
     
  try{
        Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
       PreparedStatement pst = conn.prepareStatement("Select * from calation");
    
    rs=pst.executeQuery();
    //pst.execute();
    jTable1_pumpdata.setModel(DbUtils.resultSetToTableModel(rs));
            
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     
  }
  catch(Exception e) {
                   }
      } 

}
    
       private void UpdateJTable2(){
           
            
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        cmd_search = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmd_add = new javax.swing.JButton();
        cmd_edit = new javax.swing.JButton();
        cmd_deleta = new javax.swing.JButton();
        cmd_clear = new javax.swing.JButton();
        cmd_refresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        contact2 = new javax.swing.JTextField();
        Roles = new javax.swing.JTextField();
        Desig = new javax.swing.JTextField();
        Remarks = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_pumpdata = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        agency = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jb1 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txt_search1 = new javax.swing.JTextField();
        cmd_search1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        cmd_add1 = new javax.swing.JButton();
        cmd_edit1 = new javax.swing.JButton();
        cmd_deleta1 = new javax.swing.JButton();
        cmd_clear1 = new javax.swing.JButton();
        cmd_refresh1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pd1 = new javax.swing.JTextField();
        pd2 = new javax.swing.JTextField();
        ad1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ad2 = new javax.swing.JTextField();
        remarks = new javax.swing.JTextField();
        ttime = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        allc = new javax.swing.JComboBox();
        fromdate = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        todate = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("search"));

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        cmd_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_searchActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commands", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 15), new java.awt.Color(0, 0, 153))); // NOI18N

        cmd_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC1/PIC/Button-Add-icon.png"))); // NOI18N
        cmd_add.setText("  Add");
        cmd_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_addActionPerformed(evt);
            }
        });

        cmd_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC1/PIC/Files-Edit-file-icon (1).png"))); // NOI18N
        cmd_edit.setText("Update");
        cmd_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_editActionPerformed(evt);
            }
        });

        cmd_deleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC1/PIC/bin-2-icon.png"))); // NOI18N
        cmd_deleta.setText("Delete");
        cmd_deleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deletaActionPerformed(evt);
            }
        });

        cmd_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC1/PIC/Actions-edit-clear-icon (1).png"))); // NOI18N
        cmd_clear.setText("Clear");
        cmd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_clearActionPerformed(evt);
            }
        });

        cmd_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC1/PIC/Button-Refresh-icon (1).png"))); // NOI18N
        cmd_refresh.setText("Refresh");
        cmd_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmd_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_deleta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_deleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_refresh)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Email");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel5.setText("Contact");

        jLabel6.setText("Contact2");

        jLabel7.setText("Roles");

        jLabel8.setText("Designation");

        Desig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesigActionPerformed(evt);
            }
        });

        jTable1_pumpdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Position", "FName", "LName", "Email", "Contact", "Contact", "Roles", "Designation", "Remarks", "Agency"
            }
        ));
        jTable1_pumpdata.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTable1_pumpdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_pumpdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_pumpdata);

        jLabel1.setText("Remarks");

        jLabel9.setText("Agency");

        jLabel10.setText("Position");

        jb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select User Level", "L1", "L2", "L3", "L4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Remarks, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Desig, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Roles, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contact2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobile, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb1, javax.swing.GroupLayout.Alignment.LEADING, 0, 131, Short.MAX_VALUE)
                    .addComponent(agency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contact2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Roles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Desig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Remarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(agency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_search))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Information", jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("search"));

        txt_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search1ActionPerformed(evt);
            }
        });
        txt_search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search1KeyReleased(evt);
            }
        });

        cmd_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_search1ActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commands", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 15), new java.awt.Color(0, 0, 153))); // NOI18N

        cmd_add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC1/PIC/Button-Add-icon.png"))); // NOI18N
        cmd_add1.setText("  Add");
        cmd_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add1ActionPerformed(evt);
            }
        });

        cmd_edit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC1/PIC/Files-Edit-file-icon (1).png"))); // NOI18N
        cmd_edit1.setText("Update");
        cmd_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_edit1ActionPerformed(evt);
            }
        });

        cmd_deleta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC1/PIC/bin-2-icon.png"))); // NOI18N
        cmd_deleta1.setText("Delete");
        cmd_deleta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleta1ActionPerformed(evt);
            }
        });

        cmd_clear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC1/PIC/Actions-edit-clear-icon (1).png"))); // NOI18N
        cmd_clear1.setText("Clear");
        cmd_clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_clear1ActionPerformed(evt);
            }
        });

        cmd_refresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC1/PIC/Button-Refresh-icon (1).png"))); // NOI18N
        cmd_refresh1.setText("Refresh");
        cmd_refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_refresh1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmd_edit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_add1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_deleta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_clear1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_refresh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_add1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_edit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_deleta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_clear1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_refresh1)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel11.setText("PD Start Time");

        jLabel12.setText("PD End Time");

        jLabel13.setText("AD Start Time");

        ad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad1ActionPerformed(evt);
            }
        });

        jLabel14.setText("AD End Time");

        jLabel15.setText("All Checks");

        jLabel16.setText("Remarks");

        jLabel17.setText("Transaction Time");

        ttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttimeActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "PD Start Time", "PD End Time", "AD Start Time", "AD End Time", "All Checks", "Remarks", "Transaction Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jLabel20.setText("Date");

        allc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Checks", "Yes", "No" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser4, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(pd1)
                            .addComponent(pd2)
                            .addComponent(ad1)
                            .addComponent(ad2)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ttime)
                            .addComponent(allc, 0, 204, Short.MAX_VALUE)
                            .addComponent(remarks))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(pd1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(pd2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(ad1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel14))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(allc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel17))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ttime))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jLabel18.setText("From Date");

        jLabel19.setText("To Date");

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txt_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel18)
                        .addGap(26, 26, 26)
                        .addComponent(fromdate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(todate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_search1)
                                .addComponent(jLabel19)
                                .addComponent(cmd_search1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(fromdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(todate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Plan  Time", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1305, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased

        if(txt_search.getText().isEmpty()){

            cmd_search.setBackground(Color.red);
        }else{

            cmd_search.setBackground(Color.GRAY);
        }

        try{
            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
            PreparedStatement pst = conn.prepareStatement("select * from calation where Fname=?");

            pst.setString(1,txt_search.getText());

            rs=pst.executeQuery();
            // pst.execute();
            if(rs.next()){
                
                String add2=rs.getString("Fname");
                lname.setText(add2);
                String add3=rs.getString("Lname");
                fname.setText(add3);
                String add4=rs.getString("Email");
                email.setText(add4);

                String add5=rs.getString("Contact");
                mobile.setText(add5);
                String add6=rs.getString("Contact_Landline");
                contact2.setText(add6);
                String add7=rs.getString("Roles");
                Roles.setText(add7);
                String add8=rs.getString("Designation");
                Desig.setText(add8);

                String add9=rs.getString("Remarks");
                Remarks.setText(add9);
                String add10=rs.getString("Agency");
                agency.setText(add10);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }finally {
            try{
                rs.close();
                pst.close();
                //conn.close();
            }
            catch(Exception e) {
            }
        }

        try{
            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
            PreparedStatement pst = conn.prepareStatement("select * from calation where Fname=? ");

            pst.setString(1,txt_search.getText());

            rs=pst.executeQuery();
            // pst.execute();
            if(rs.next()){
                
                String add2=rs.getString("Lname");
                lname.setText(add2);
                String add3=rs.getString("Fname");
                fname.setText(add3);
                String add4=rs.getString("Email");
                email.setText(add4);

                String add5=rs.getString("Contact");
                mobile.setText(add5);
                String add6=rs.getString("Contact_Landline");
                contact2.setText(add6);
                String add7=rs.getString("Roles");
                Roles.setText(add7);
                String add8=rs.getString("Designation");
                Desig.setText(add8);

                String add9=rs.getString("Remarks");
                Remarks.setText(add9);
                String add10=rs.getString("Agency");
                agency.setText(add10);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }finally {
            try{
                rs.close();
                pst.close();
                //conn.close();
            }
            catch(Exception e) {
            }
        }

        try{

            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
            PreparedStatement pst = conn.prepareStatement("select * from calation where Lname=? ");

            pst.setString(1,txt_search.getText());

            rs=pst.executeQuery();
            // pst.execute();
            if(rs.next()){
               
              String add2=rs.getString("Lname");
                lname.setText(add2);
                String add3=rs.getString("Fname");
                fname.setText(add3);
                String add4=rs.getString("Email");
                email.setText(add4);

                String add5=rs.getString("Contact");
                mobile.setText(add5);
                String add6=rs.getString("Contact_Landline");
                contact2.setText(add6);
                String add7=rs.getString("Roles");
                Roles.setText(add7);
                String add8=rs.getString("Designation");
                Desig.setText(add8);

                String add9=rs.getString("Remarks");
                Remarks.setText(add9);
                String add10=rs.getString("Agency");
                agency.setText(add10);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }finally {
            try{
                rs.close();
                pst.close();
                //conn.close();
            }
            catch(Exception e) {
            }
        }

        try{
            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
            PreparedStatement pst = conn.prepareStatement("select * from calation where Designation=?  ");

            pst.setString(1,txt_search.getText());

            rs=pst.executeQuery();
            // pst.execute();
            if(rs.next()){
               
               String add2=rs.getString("Lname");
                lname.setText(add2);
                String add3=rs.getString("Fname");
                fname.setText(add3);
                String add4=rs.getString("Email");
                email.setText(add4);

                String add5=rs.getString("Contact");
                mobile.setText(add5);
                String add6=rs.getString("Contact_Landline");
                contact2.setText(add6);
                String add7=rs.getString("Roles");
                Roles.setText(add7);
                String add8=rs.getString("Designation");
                Desig.setText(add8);

                String add9=rs.getString("Remarks");
                Remarks.setText(add9);
                String add10=rs.getString("Agency");
                agency.setText(add10);

            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }finally {
            try{
                rs.close();
                pst.close();
                //conn.close();
            }
            catch(Exception e) {
            }
        }

    }//GEN-LAST:event_txt_searchKeyReleased

    private void cmd_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_searchActionPerformed

        try{

            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
            PreparedStatement pst = conn.prepareStatement("select * from calation where Contact=?");

            pst.setString(1,txt_search.getText());

            rs=pst.executeQuery();
            // pst.execute();
            if(rs.next()){
               String add2=rs.getString("Lname");
                lname.setText(add2);
                String add3=rs.getString("Fname");
                fname.setText(add3);
                String add4=rs.getString("Email");
                email.setText(add4);

                String add5=rs.getString("Contact");
                mobile.setText(add5);
                String add6=rs.getString("Contact_Landline");
                contact2.setText(add6);
                String add7=rs.getString("Roles");
                Roles.setText(add7);
                String add8=rs.getString("Designation");
                Desig.setText(add8);

                String add9=rs.getString("Remarks");
                Remarks.setText(add9);
                String add10=rs.getString("Agency");
                agency.setText(add10);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }finally {
            try{
                rs.close();
                pst.close();
                //conn.close();
            }
            catch(Exception e) {
            }
        }

        try{

            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
            PreparedStatement pst = conn.prepareStatement("select * from calataion where Contact_Landline=? ");

            pst.setString(1,txt_search.getText());

            rs=pst.executeQuery();
            // pst.execute();
            if(rs.next()){
               
               String add2=rs.getString("Lname");
                lname.setText(add2);
                String add3=rs.getString("Fname");
                fname.setText(add3);
                String add4=rs.getString("Email");
                email.setText(add4);

                String add5=rs.getString("Contact");
                mobile.setText(add5);
                String add6=rs.getString("Contact_Landline");
                contact2.setText(add6);
                String add7=rs.getString("Roles");
                Roles.setText(add7);
                String add8=rs.getString("Designation");
                Desig.setText(add8);

                String add9=rs.getString("Remarks");
                Remarks.setText(add9);
                String add10=rs.getString("Agency");
                agency.setText(add10);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }finally {
            try{
                rs.close();
                pst.close();
                //conn.close();
            }
            catch(Exception e) {
            }
        }

        try{

            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
            PreparedStatement pst = conn.prepareStatement("select * from calation where Agency=");

            pst.setString(1,txt_search.getText());

            rs=pst.executeQuery();
            // pst.execute();
            if(rs.next()){

             String add2=rs.getString("Lname");
                lname.setText(add2);
                String add3=rs.getString("Fname");
                fname.setText(add3);
                String add4=rs.getString("Email");
                email.setText(add4);

                String add5=rs.getString("Contact");
                mobile.setText(add5);
                String add6=rs.getString("Contact_Landline");
                contact2.setText(add6);
                String add7=rs.getString("Roles");
                Roles.setText(add7);
                String add8=rs.getString("Designation");
                Desig.setText(add8);

                String add9=rs.getString("Remarks");
                Remarks.setText(add9);
                String add10=rs.getString("Agency");
                agency.setText(add10);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }finally {
            try{
                rs.close();

                pst.close();
                //conn.close();
            }
            catch(Exception e) {
            }
        }

    }//GEN-LAST:event_cmd_searchActionPerformed

    private void cmd_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_addActionPerformed

        
        
        
        
        String position=(jb1.getSelectedItem().toString());
        String name1=fname.getText();
        String name2=lname.getText();
        String email1=email.getText();
        String mobile1=mobile.getText();
        String Designation=contact2.getText();
        String Group1=Roles.getText();
        String division=Desig.getText();
        String uid=Remarks.getText();
        String sno=agency.getText();
       
        

        try{

            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");

            Statement pst =(Statement) conn.createStatement();
            String query = "INSERT INTO calation VALUES('"+position+"','"+name1+"','"+name2+"','"+email1+"','"+mobile1+"','"+Designation+"','"+Group1+"','"+division+"','"+uid+"','"+sno+"'); ";

            pst.executeUpdate(query);

            // rs=pst.executeQuery()txt_dob;

            JOptionPane.showMessageDialog(null, "Saved");
            //administrator_windows_JForm s = new administrator_windows_JForm();
            //s.setVisible(true);

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }finally {
            try{
                rs.close();
                pst.close();
                // conn.close();
            }
            catch(Exception e) {
            }
        }
    }//GEN-LAST:event_cmd_addActionPerformed

    private void cmd_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_editActionPerformed
        try{
            String position=(jb1.getSelectedItem().toString());
            String value2=fname.getText();
            String value3=lname.getText();
          // Collecting the input
            

            String value6=email.getText();
            String value7=mobile.getText();
            String value8=contact2.getText();
            String value9=Roles.getText();
            String value10=Desig.getText();
              String value4=Remarks.getText();
            String value5 = agency.getText(); 

            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");

            Statement pst =(Statement) conn.createStatement();
            String query = "update calation set Position='"+position+"',Fname='"+value2+"',Lname='"+value3+"',Email='"+value6+"',Contact='"+value7+"',Contact_Landline='"+value8+"',Roles='"+value9+"',Designation='"+value10+"',Remarks='"+value4+"',Agency='"+value5+"' where Email='"+value6+"';";

            pst.executeUpdate(query);

            JOptionPane.showMessageDialog(null, "Updated");
            //QueryJFrame s = new QueryJFrame();
            //s.setVisible(true);

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }finally {
            try{
                rs.close();
                pst.close();
                // conn.close();
            }
            catch(Exception e) {
            }
        }
    }//GEN-LAST:event_cmd_editActionPerformed

    private void cmd_deletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deletaActionPerformed

         String position=(jb1.getSelectedItem().toString());
            String value2=fname.getText();
            String value3=lname.getText();
          // Collecting the input
            

            String value6=email.getText();
            String value7=mobile.getText();
            String value8=contact2.getText();
            String value9=Roles.getText();
            String value10=Desig.getText();
              String value4=Remarks.getText();
            String value5 = agency.getText(); 
        try{
            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
           
             
            Statement pst =(Statement) conn.createStatement();
       String query = "delete from calation where Email='"+value6+"'AND Fname='"+value2+"'AND Contact='"+value7+"' ;";


            pst.executeUpdate(query);


          
            JOptionPane.showMessageDialog(null, "Deleted");
            //QueryJFrame s = new QueryJFrame();
            //s.setVisible(true);

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }finally {
            try{
                rs.close();
                pst.close();
                //conn.close();
            }
            catch(Exception e) {
            }
        }
    }//GEN-LAST:event_cmd_deletaActionPerformed

    private void cmd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_clearActionPerformed
       
        
        fname.setText("");
        lname.setText("");

        Remarks.setText("");
        agency.setText("");
        contact2.setText("");
        mobile.setText("");
        Roles.setText("");
        Desig.setText("");
        email.setText("");

    }//GEN-LAST:event_cmd_clearActionPerformed

    private void cmd_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_refreshActionPerformed
        UpdateJTable();
    }//GEN-LAST:event_cmd_refreshActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void DesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesigActionPerformed

    private void jTable1_pumpdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_pumpdataMouseClicked

        int row =jTable1_pumpdata.getSelectedRow();
        jb1.setSelectedItem(jTable1_pumpdata.getModel().getValueAt(row, 0).toString());
        
        
        fname.setText(jTable1_pumpdata.getModel().getValueAt(row, 1).toString());
        lname.setText(jTable1_pumpdata.getModel().getValueAt(row, 2).toString());
        email.setText(jTable1_pumpdata.getModel().getValueAt(row, 3).toString());
        mobile.setText(jTable1_pumpdata.getModel().getValueAt(row, 4).toString());
        contact2.setText(jTable1_pumpdata.getModel().getValueAt(row, 5).toString());
        Roles.setText(jTable1_pumpdata.getModel().getValueAt(row, 6).toString());
        Desig.setText(jTable1_pumpdata.getModel().getValueAt(row, 7).toString());
        Remarks.setText(jTable1_pumpdata.getModel().getValueAt(row, 8).toString());
        agency.setText(jTable1_pumpdata.getModel().getValueAt(row, 9).toString());
       
    }//GEN-LAST:event_jTable1_pumpdataMouseClicked

    private void txt_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1ActionPerformed

    private void txt_search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1KeyReleased

    private void cmd_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_search1ActionPerformed

    private void cmd_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add1ActionPerformed
        java.sql.Date date=new java.sql.Date(jDateChooser4.getDate().getTime());
       
       
        String name1=pd1.getText();
        String name2=pd2.getText();
        String email1=ad1.getText();
        String mobile1=ad2.getText();
       String Designation=(allc.getSelectedItem().toString());
        String Group1=remarks.getText();
        String division=ttime.getText();
        
        

        try{

            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");

            Statement pst =(Statement) conn.createStatement();
            String query = "INSERT INTO application_infra VALUES('"+date+"','"+name1+"','"+name2+"','"+email1+"','"+mobile1+"','"+Designation+"','"+Group1+"','"+division+"'); ";

            pst.executeUpdate(query);

            // rs=pst.executeQuery()txt_dob;

            JOptionPane.showMessageDialog(null, "Saved");
            //administrator_windows_JForm s = new administrator_windows_JForm();
            //s.setVisible(true);

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Only One DownTime A Day is Allowed");

        }finally {
            try{
                rs.close();
                pst.close();
                // conn.close();
            }
            catch(Exception e) {
            }
        }
        
















// TODO add your handling code here:
    }//GEN-LAST:event_cmd_add1ActionPerformed

    private void cmd_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_edit1ActionPerformed
  try{
        java.sql.Date date=new java.sql.Date(jDateChooser4.getDate().getTime());
            
            String value2=pd1.getText();
            String value3=pd2.getText();
          // Collecting the input
            

            String value6=ad1.getText();
            String value7=ad2.getText();
            String position=(allc.getSelectedItem().toString());
            String value8=remarks.getText();
            String value9=ttime.getText();
           

            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");

            Statement pst =(Statement) conn.createStatement();
            String query = "update application_infra set Date='"+date+"',Plant_Downtime_Start_Time='"+value2+"',Plant_Downtime_End_Time='"+value3+"',Actual_Downtime_Start_Time='"+value6+"',Actual_Downtime_End_Time='"+value7+"',All_Check='"+position+"',Remarks='"+value8+"',Transaction_Time='"+value9+"'where Date='"+date+"';";

            pst.executeUpdate(query);

            JOptionPane.showMessageDialog(null, "Updated");
            //QueryJFrame s = new QueryJFrame();
            //s.setVisible(true);

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }finally {
            try{
                rs.close();
                pst.close();
                // conn.close();
            }
            catch(Exception e) {
            }
        }
        



// TODO add your handling code here:
    }//GEN-LAST:event_cmd_edit1ActionPerformed

    private void cmd_deleta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleta1ActionPerformed
         java.sql.Date date=new java.sql.Date(jDateChooser4.getDate().getTime());
        try{
            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
           
             
            Statement pst =(Statement) conn.createStatement();
       String query = "delete from application_infra where Date='"+date+"';";


            pst.executeUpdate(query);

          

            JOptionPane.showMessageDialog(null, "Deleted");
            //QueryJFrame s = new QueryJFrame();
            //s.setVisible(true);

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }finally {
            try{
                rs.close();
                pst.close();
                //conn.close();
            }
            catch(Exception e) {
            }
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_cmd_deleta1ActionPerformed

    private void cmd_clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_clear1ActionPerformed
pd1.setText("");
        pd2.setText("");
        ad1.setText("");

        ad2.setText("");
        
        remarks.setText("");
        ttime.setText("");
       
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_cmd_clear1ActionPerformed

    private void cmd_refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_refresh1ActionPerformed
UpdateJTable2();
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_refresh1ActionPerformed

    private void ad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad1ActionPerformed

    private void ttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttimeActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        int row =jTable2.getSelectedRow();
        jDateChooser4.setDate((java.util.Date) jTable2.getModel().getValueAt(row, 0));
        pd1.setText(jTable2.getModel().getValueAt(row, 1).toString());
        pd2.setText(jTable2.getModel().getValueAt(row, 2).toString());
        ad1.setText(jTable2.getModel().getValueAt(row, 3).toString());
        ad2.setText(jTable2.getModel().getValueAt(row, 4).toString());
        allc.setSelectedItem(jTable2.getModel().getValueAt(row, 5).toString());
        remarks.setText(jTable2.getModel().getValueAt(row, 6).toString());
        ttime.setText(jTable2.getModel().getValueAt(row, 7).toString());
        
       
        





// TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 java.sql.Date date1=new java.sql.Date(fromdate.getDate().getTime());
               java.sql.Date date2=new java.sql.Date(todate.getDate().getTime());
        
        
        //jTable1_pumpdata.setBackground((Color.GREEN));
         
     
  try{
        Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db?" + "user=root&password=");
       PreparedStatement pst = conn.prepareStatement("Select * from application_infra where Date Between'"+date1+"' AND '"+date2+"'  ");
    
    rs=pst.executeQuery();
    //pst.execute();
    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     
  }
  catch(Exception e) {
                   }
      } 

        






// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscalationMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscalationMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscalationMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscalationMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscalationMatrix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Desig;
    private javax.swing.JTextField Remarks;
    private javax.swing.JTextField Roles;
    private javax.swing.JTextField ad1;
    private javax.swing.JTextField ad2;
    private javax.swing.JTextField agency;
    private javax.swing.JComboBox allc;
    private javax.swing.JButton cmd_add;
    private javax.swing.JButton cmd_add1;
    private javax.swing.JButton cmd_clear;
    private javax.swing.JButton cmd_clear1;
    public static javax.swing.JButton cmd_deleta;
    public static javax.swing.JButton cmd_deleta1;
    public static javax.swing.JButton cmd_edit;
    private javax.swing.JButton cmd_edit1;
    private javax.swing.JButton cmd_refresh;
    private javax.swing.JButton cmd_refresh1;
    private javax.swing.JButton cmd_search;
    private javax.swing.JButton cmd_search1;
    private javax.swing.JTextField contact2;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private com.toedter.calendar.JDateChooser fromdate;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1_pumpdata;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox jb1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField pd1;
    private javax.swing.JTextField pd2;
    private javax.swing.JTextField remarks;
    private com.toedter.calendar.JDateChooser todate;
    private javax.swing.JTextField ttime;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_search1;
    // End of variables declaration//GEN-END:variables

    
}
